### ISSUE TITLE
openssl_decrypt error : “failed to base64 decode the input”

### ISSUE THREAD

**Issue by chasegiunta** [miranj/craft-cryptographer#1]
`openssl_decrypt error : “failed to base64 decode the input”`
I seem to get this error randomly, 1 out of 6 times or so, when trying to use the default `decrypt` & `encrypt` filters. Luckily, using `AES-128-CFB` for enc / dec has stopped the error.

**Comment by rungta** [comment]
I could be wrong, but this [sounds like a URL encoding issue](http://stackoverflow.com/questions/33127515/occasional-openssl-decrypt-error-failed-to-base64-decode-the-input). Was the encrypted string (the output of `encrypt`) being passed on to `decrypt` via a URL at any point?

If yes, then can you try URL encoding the encrypted string using the [`url_encode`](http://twig.sensiolabs.org/doc/filters/url_encode.html) Twig filter and see if the error persists?
