### ISSUE TITLE
Any updates for Craftcms 5?

### ISSUE THREAD

**Issue by samdi** [miranj/craft-cryptographer#10]
I wondered if Cryptographer will be ready for Craftcms 5. I want to try Craftcms 5, so is there any way to make Cryptographer compatible with Craftcms 5?

**Comment by rungta** [comment]
We plan on updating all our plugins to support Craft 5. We’re targeting getting this done in April.

**Comment by samdi** [comment]
> We plan on updating all our plugins to support Craft 5. We’re targeting getting this done in April.

Great news, waiting for the best cryptographer plugin for craftcms 5. Thanks for your updates.

**Comment by rungta** [comment]
We’ve just released [v1.2.0 of the plugin](https://github.com/miranj/craft-cryptographer/releases/tag/v1.2.0) which adds support for Craft 5.

Thank you for your patience @samdi.
