### ISSUE TITLE
Can't install with Craft CMS 3.2.6 

### ISSUE THREAD

**Issue by EternalBlack** [miranj/craft-cryptographer#2]
Whenever I try to install this plugin on a fresh/clean install for Craft CMS 3.2.6 I receive
> Error
> Class 'Craft\base\Plugin' not found

I have another system that has the plugin already installed for a while and is on the same Craft CMS version. Uninstalling it there and reinstalling it works just fine there.

This is what I could find inside the logs:

> 019-07-25 02:08:46 [90.187.46.237][-][9uqpp5kd4tjetv2800ephi81ft][error][Error] Error: Class 'Craft\base\Plugin' not found in MY_PATH_HERE/httpdocs/vendor/miranj/craft-cryptographer/src/Plugin.php:19
> Stack trace:
> #0 MY_PATH_HERE/httpdocs/vendor/composer/ClassLoader.php(444): include()
> #1 MY_PATH_HERE/httpdocs/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/vhosts...')
> #2 [internal function]: Composer\Autoload\ClassLoader->loadClass('miranj\\cryptogr...')
> #3 [internal function]: spl_autoload_call('miranj\\cryptogr...')
> #4 MY_PATH_HERE/httpdocs/vendor/craftcms/cms/src/services/Plugins.php(870): is_subclass_of('miranj\\cryptogr...', 'craft\\base\\Plug...')
> #5 MY_PATH_HERE/httpdocs/vendor/craftcms/cms/src/services/Plugins.php(230): craft\services\Plugins->createPlugin('cryptographer', Array)
> #6 MY_PATH_HERE/httpdocs/vendor/craftcms/cms/src/base/ApplicationTrait.php(1323): craft\services\Plugins->loadPlugins()
> #7 MY_PATH_HERE/httpdocs/vendor/craftcms/cms/src/web/Application.php(112): craft\web\Application->_postInit()
> #8 MY_PATH_HERE/httpdocs/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
> #9 MY_PATH_HERE/httpdocs/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
> #10 MY_PATH_HERE/httpdocs/vendor/craftcms/cms/src/web/Application.php(100): yii\base\Application->__construct(Array)
> #11 [internal function]: craft\web\Application->__construct(Array)
> #12 MY_PATH_HERE/httpdocs/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
> #13 MY_PATH_HERE/httpdocs/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
> #14 MY_PATH_HERE/httpdocs/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
> #15 MY_PATH_HERE/httpdocs/vendor/craftcms/cms/bootstrap/bootstrap.php(248): yii\BaseYii::createObject(Array)
> #16 MY_PATH_HERE/httpdocs/vendor/craftcms/cms/bootstrap/web.php(52): require('/var/www/vhosts...')
> #17 MY_PATH_HERE/httpdocs/web/index.php(20): require('/var/www/vhosts...')
> #18 {main}
> 2019-07-25 02:08:46 [90.187.46.237][-][9uqpp5kd4tjetv2800ephi81ft][info][application] $_GET = [
>     'p' => 'admin/actions/pluginstore/install/migrate'
> ]

**Comment by rungta** [comment]
Fixed in [1.0.1](https://github.com/miranj/craft-cryptographer/releases/tag/v1.0.1). Thanks for reporting!
