### ISSUE TITLE
New tag with the v4 hashids change?

### ISSUE THREAD

**Issue by martyspain** [miranj/craft-cryptographer#5]
The version of the plugin on Packagist is 1.0.3 which does not contain the [change](https://github.com/miranj/craft-cryptographer/commit/967cbcae1339c1a581082e2f767ac58660651b0d) to allow version 4 of hashids. Is it possible to  publish a new tag with this change in?

**Comment by rungta** [comment]
Done. Thanks for the reminder @martyspain!

**Comment by martyspain** [comment]
No worries! Thanks for the incredibly speedy response.
