### ISSUE TITLE
Inquiry - Mask Number permanence 

### ISSUE THREAD

**Issue by sg-modlab** [miranj/craft-cryptographer#8]
Exploring this plugin for a project and have a question. Reviewed the documentation and it seems that the maskNumbers filter will result in a string that is permanent. That over time if applied to the same number, you'd always get the same string when filter is applied. Is this accurate?

Over time is there anything you could envision that might result in the string the filter produces changing?

**Comment by rungta** [comment]
That is correct @sg-modlab. Given the same input, `maskNumbers` should always return the same output. However, if you want to dig deeper into this (and verify this contract), you should really check out [the underlying Hashids library](https://hashids.org/php/) that `maskNumbers` is simply a wrapper for.

**Comment by rungta** [comment]
Just FYI, there are three parameters passed on to the Hashids constructor: https://github.com/miranj/craft-cryptographer/blob/63ac9cb60fc404fddbcbc923873c83a8c0cf092f/src/services/Cryptographer.php#L33-L43

1. [Your security key](https://craftcms.com/docs/3.x/installation.html#step-3-set-a-security-key), used as the salt
2. [Minimum length, or padding](https://github.com/vinkla/hashids#use-padding-to-make-your-output-ids-longer)
3. [The alphabet](https://github.com/vinkla/hashids#using-a-custom-alphabet)

As long as all three of them remain the same, the output should be permanent.

**Comment by sg-modlab** [comment]
And it is my understanding the plugin uses Craft's security key, correct. Only should add one to the config if this was used previously on a Craft 2 site.

**Comment by rungta** [comment]
That is correct.
